/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Municipio de Gye
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        gua2 = new javax.swing.JButton();
        vr2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        mostar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuestionario-Federación Madrileña de Karate");

        jLabel2.setText("Cuestionario de 2do Nivel Dan");

        gua2.setText("Guardar");
        gua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gua2ActionPerformed(evt);
            }
        });

        vr2.setText("Verificar Respuestas");
        vr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vr2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Respuesta:");

        jLabel4.setText("Pregunta:");

        mostar.setText("Mostrar Preguntas");
        mostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Cuestionario");

        ta2.setColumns(20);
        ta2.setRows(5);
        jScrollPane1.setViewportView(ta2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(gua2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vr2))
                    .addComponent(t2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mostar))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel5)))
                        .addGap(0, 268, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mostar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gua2)
                    .addComponent(vr2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostarActionPerformed
 File archivo = new File("C:\\Users\\Bryan Alava\\Downloads\\Proyecto\\Preguntas\\Preguntas Nivel 2.txt");   
    
      try {
          BufferedReader leer =new BufferedReader(new FileReader(archivo));
            String linea=leer.readLine();
            while(linea!=null){
                ta2.append(linea+"\n");
                linea=leer.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
        }  
JOptionPane.showMessageDialog(this,
                            "\"Conteste las preguntas en la casila de respuestas segun el literal que crea usted que es el correcto.\n Ej: a,b,d,c,etc" , "tips ",
                            JOptionPane.INFORMATION_MESSAGE);      // TODO add your handling code here:
    }//GEN-LAST:event_mostarActionPerformed

    private void gua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gua2ActionPerformed
try {
        FileWriter respuesta = new FileWriter("C:\\Users\\Bryan Alava\\Downloads\\Proyecto\\Preguntas\\mis respuestas nivel 2.txt");
        String texto= t2.getText().replace("\n","\r\n");
        PrintWriter imprime = new PrintWriter(respuesta);
        imprime.print(texto);
        respuesta.close();
    } catch (Exception ex) {
        Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
       }
        
try{
     JOptionPane.showMessageDialog(this,
             "Se han guardado tus respuestas.", "Listo",
                     JOptionPane.INFORMATION_MESSAGE);
   }catch(Exception e){
        JOptionPane.showMessageDialog(this,
                            "No se han podido guardar tus respuestas.", "Error",
                            JOptionPane.ERROR_MESSAGE);
                    
     }           // TODO add your handling code here:
    }//GEN-LAST:event_gua2ActionPerformed

    private void vr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vr2ActionPerformed
try{
     
           JOptionPane.showMessageDialog(this,
                            "Se han verificado tus respuestas, pasaste.", "Aprobado",
                            JOptionPane.INFORMATION_MESSAGE);
     }catch(Exception e){
        JOptionPane.showMessageDialog(this,
                            "No se han verificado tus respuestas,lo sentimos has reprobado.", "Reprobado",
                            JOptionPane.ERROR_MESSAGE);
                    
     }         // TODO add your handling code here:
    }//GEN-LAST:event_vr2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gua2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostar;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea ta2;
    private javax.swing.JButton vr2;
    // End of variables declaration//GEN-END:variables
}
